{% set name = "datadog" %}
{% set version = "0.50.1" %}
{% set sha256 = "579d4db54bd6ef918c5250217edb15b80b7b11582b8e24fce43702768c3f2e2d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dog = datadog.dogshell:main
    - dogwrap = datadog.dogshell.wrap:main

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - decorator >=3.3.2
    - requests >=2.6.0

test:
  imports:
    - datadog
    - datadog.dogshell
  commands:
    - dog --help
    - dogwrap --help

about:
  home: https://github.com/DataDog/datadogpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Datadog Python library

  description: |
    The Python integration enables you to monitor any custom metric by instrumenting a few lines of code.
  doc_url: https://docs.datadoghq.com/integrations/python/

extra:
  recipe-maintainers:
    - mariusvniekerk
