{% set name = "datadog" %}
{% set version = "0.25.0" %}
{% set sha256 = "e71f9024fb0b968bd704178c7e48fa41ce728281cc6913994db5e065596cddf1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - dog = datadog.dogshell:main
    - dogwrap = datadog.dogshell.wrap:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - decorator >=3.3.2
    - requests >=2.6.0
    - simplejson >=2.0.9

test:
  imports:
    - datadog
    - datadog.dogshell
  commands:
    - dog --help
    - dogwrap --help

about:
  home: https://github.com/DataDog/datadogpy
  license: BSD-3-Clause
  license_family: BSD
  summary: 'The Datadog Python library'

  description: |
    The Python integration enables you to monitor any custom metric by instrumenting a few lines of code.
  doc_url: https://docs.datadoghq.com/integrations/python/

extra:
  recipe-maintainers:
    - TheOriginalAlex
    - mariusvniekerk
